version: '3'
services:
  style-fixer:
    image: designmynight/php7.1-style-enforcer:latest
    entrypoint: ["phpcbf"]
    volumes:
      - .:/opt
  unit-tests:
    image: designmynight/php7.1-cli-mongo
    command: phpdbg -qrr ./vendor/bin/phpunit
    volumes:
      - .:/opt
    working_dir: /opt
